*&---------------------------------------------------------------------*
*& Include          ZBC_TRANSPORT_UP_DOWN_SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b01 WITH FRAME TITLE vt_b01.
  " --- Transportauftrag
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(25) vt_ta FOR FIELD p_ta MODIF ID z01.
    PARAMETERS p_ta TYPE e070-trkorr OBLIGATORY.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(25) vt_frnt FOR FIELD p_frnt.
    PARAMETERS p_frnt TYPE rlgrap-filename DEFAULT 'c:\temp'.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(25) vt_appl FOR FIELD p_appl.
    PARAMETERS p_appl TYPE authb-filename OBLIGATORY.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF BLOCK b02 WITH FRAME TITLE vt_b02.
    " ---> Frontend --> Application
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(25) vt_r01 FOR FIELD p_r01.
      PARAMETERS p_r01 RADIOBUTTON GROUP r1 DEFAULT 'X' MODIF ID z02 USER-COMMAND rb1.
    SELECTION-SCREEN END OF LINE.
    " ---> Application --> Frontend
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(25) vt_r02 FOR FIELD p_r02.
      PARAMETERS p_r02 RADIOBUTTON GROUP r1.
    SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK b02.
  SELECTION-SCREEN BEGIN OF BLOCK b03 WITH FRAME TITLE vt_b03.
    " --- APPEND
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(33) vt_appen FOR FIELD p_append MODIF ID z03.
      PARAMETERS p_append TYPE char1 AS CHECKBOX                MODIF ID z03.
    SELECTION-SCREEN END OF LINE.
    " --- IMPORT
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(33) vt_impo FOR FIELD p_import MODIF ID z03.
      PARAMETERS p_import TYPE char1 AS CHECKBOX               MODIF ID z03.
    SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN END OF BLOCK b03.
SELECTION-SCREEN END OF BLOCK b01.
